- app.js
> Make Sentry module optional

- routes/api.js
- src/components/Form/Signup/EmailChinese.js
- src/components/Signup.js
Those IPs skip the captcha test for now.
We need to choose a captcha provider that will be implemented later.
This PR will remain a WIP while #124 isn't validated as the conveyor will block on email step
> Remove Google ReCaptcha for Chinese IPs.

- helpers/steemconnect-templates.json
- helpers/templates.json
Replacing SteemConnect with Steemit and updated messaging as per discussion with @jredbeard
> Updated email messaging

- db/migrations/create-users.js
Changes:
- Remove default value from fingerprint field
> Fix sequelize migration script

- .env.example
- README.md
- app.js
- helpers/getClientConfig.js
- package.json
- src/components/CreateAccount.js
- src/components/Form/Signup/Email.js
- src/store.js
- views/index.hbs
- webpack/makeConfig.js
closes #149
also:
add default redirect uri to .env.example
no nodemon in production
> inject client-side config at runtime

- app.js
- app.json
- package.json
- yarn.lock
> Remove Raven/Sentry

- helpers/mail.js
- routes/api.js
- src/components/Form/Signup/ConfirmPhoneNumber.js
- src/components/Form/Signup/Email.js
- src/components/Form/Signup/EmailChinese.js
- src/components/Form/Signup/PhoneNumber.js
- src/components/Form/Signup/Username.js
- src/utils/api.js
Fixes #143, Fixes #156 
Supersedes #162
> Use async API handlers

- routes/api.js
- src/components/CreateAccount.js
- src/components/Form/Signup/ConfirmPhoneNumber.js
- src/components/Form/Signup/Email.js
- src/components/Form/Signup/EmailChinese.js
- src/components/Form/Signup/PhoneNumber.js
> Change API methods to post whenever necessary

- app.json
- circle.yml
- package.json
> Fix package information

- routes/api.js
- yarn.lock
STEEMJS_URL env var is now used both client and server side
> Use jussi for talking to conveyor

- src/components/Signup.js
> default referrer to steemit

- routes/api.js
- src/components/Form/Signup/PhoneNumber.js
> Better phone number validation and error handling

- src/locales/en.json
This is a resubmit of PR 198 under a local branch.
> Let users know it may take time to review account

- routes/api.js
Fix bug where numbers with dashes would be passed to conveyor
> Ensure only valid numbers are passed to conveyor

- README.md
Because white is the best kind of space
> Add whitespace to readme

- src/components/Form/Signup/Username.js
> Normalize the username input so that the content is returned in lowercase

- admin/public/css/app.css
- admin/routes/index.js
- admin/views/pages/users.ejs
- admin/views/partials/layout/menu.ejs
- admin/views/search.ejs
Merge in some updates that had happened in faucet-admin since the merge (search & pagination)
> Add latest faucet-admin features

- routes/api.js
I don't know if this is enough to solve the complete issue and every use cases but it should solve an invalid token case
#246
> Remove the 7 days token expiry

- helpers/twilio.js
- routes/api.js
Rationale described here:
https://github.com/steemit/faucet/issues/234#issuecomment-372754290
> add phone number validation, use E164 formatting, refs #234

- helpers/mail.js
> fix lint errors in helpers/mail.js

- admin/routes/index.js
- admin/views/components/user-modal.ejs
- admin/views/dashboard.ejs
- admin/views/pages/users.ejs
- admin/views/partials/layout/menu.ejs
- admin/views/user.ejs
- db/seeders/users-data.js
- helpers/templates.json
- routes/api.js
> Re-send email to lost users, refs #259

- .gitignore
we have `.env-admin`, let's not commit that, ever ey?
> ommit .env* from git

- admin/routes/index.js
- admin/views/dashboard.ejs
- db/config/config.json
- db/seeders/users-data.js
Find out number of users who have no attempt to verify.
> get a count of approved users with no email attempt, refs #259

- src/components/ConfirmEmail.js
- src/components/CreateAccount.js
- src/components/Form/Signup/ConfirmPhoneNumber.js
- src/components/Form/Signup/Email.js
- src/components/Form/Signup/EmailChinese.js
- src/components/Form/Signup/PhoneNumber.js
- src/components/Form/Signup/Username.js
- src/components/Signup.js
- src/containers/app.js
- src/styles/theme.less
This reverts commit e51461615fb1cfb58cdc0dfdfdcf70b68e80d52c, reversing
changes made to c63f5d2def307a51956e7cc78743ec1784733250.
> Revert "Merge pull request #276 from steemit/im/254/dev-query-param"

- src/components/CreateAccount.js
- src/components/Form/CreateAccount/Password.js
closes #286  
add a missing `key` to an iterated react element
remove unnecessary & output-polluting eslint-enable/disable
remove un-rendered and un-necessary textarea element attributes
> some small bugfixes

- routes/apiHandlers.js
> Log numbers tried during signup attempt

- LICENSE
Need to trigger a rebuild of master
> Add license year

- package.json
- yarn.lock
it is unmaintained - we can re-implement after https://github.com/steemit/steempunks/issues/373
> remove nsp

- admin/src/components/dashboard.tsx
- admin/src/components/signup-detail.tsx
- routes/admin.js
- routes/apiHandlers.js
Closes #294 and add a check in case gatekeeper sends an invalid response
> Allow approvals to be made even if accounts isn't verified

- src/reducers/user.js
> supply referrer from ref get param

- src/reducers/user.js
i mis-wrote the original regex. this one actually matches the whole referrer word.
> fix regex for referrer

- routes/adminHandlers.js
- routes/adminHandlers.test.js
> Add device search

- constants.js
- src/components/Form/Signup/SignupOptions.js
- src/locales/en.json
Converted to internal branch, closing #401
> Added Steemwallet.app to paid account-creation sources

- package.json
- routes/apiHandlers.js
- yarn.lock
This will make a call to the newsletter server (if configured via env vars) to subscribe a user to a mailing list. This keeps the newsletter list 1:1 with the user database without having to manually update it.
> Add users to newsletter subscription list after account creation

- constants.js
- public/css/antd.css
- src/components/Form/Signup/SignupOptions.js
- src/locales/en.json
In organization version of: https://github.com/steemit/faucet/pull/419
> Update list of 3rd party account creation services

- src/components/Form/Signup/SignupOptions.js
> update singup options

- routes/apiHandlers.js
change sms authcode logic of API.
> change sms authcode

- package.json
- yarn.lock
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> fix git protocol upgrade
